### ISSUE TITLE
Upload Video of Presentation?

### ISSUE THREAD

**Issue by dternyak** [paxos-bankchain/moneroutil#1]
This looks like a great utility! 

I was looking forward to hearing more about it at the recent meetup, but I'm unable to find a clip.

Is it possible to provide a transcription of the speed and/or provide additional documentation on what looks like a great utility? 

Thanks :)

**Comment by jimmysong** [comment]
Unfortunately, no one recorded it. I will strive to provide more documentation as I continue work on it.
